### ISSUE TITLE
improvement: make dependsOn play nice with OverseerRestartLast

### ISSUE THREAD

**Issue by alexjwilliams** [stevearc/overseer.nvim#199]
I have the following tasks defined in a `tasks.json` file:
```json
{
"label": "configure",
"command": "..."
},
{
"label": "compile",
"command": "...",
"dependsOn": ["configure"]
},
{
"label": "run",
"command": "...",
"dependsOn": ["compile"]
}
```
If I execute `:OverseerRun run` followed by `OverseerRestartLast` (as you defined it in the docs), the task that gets restarted is "configure". This does not match VSCode's behavior. If it doesn't break anything, `overseer.list_tasks` should be changed so that `overseer.list_tasks { recent_first = true }` returns `{"run", "compile", "configure"}` after executing `"run"` with overseer.

**Comment by stevearc** [comment]
Fixed!

**Comment by alexjwilliams** [comment]
Thanks for the changes. The behavior is still not correct. If I execute `OverseerRun run` and then `OverseerRestartLast` while `"run"` is running, the tasks are restarted in the correct order. However, if I wait until `"run"` is completed before executing `OverseerRestartLast`, then the only task that gets restarted is `"configure"`. It appears that the ordering of the task list is reverting to its original form when `"run"` is completed.

**Comment by stevearc** [comment]
Apologies, the previous commit worked for a couple cases, but I see now that it was insufficient. I put in what is hopefully a more robust solution, and added a bit of a visual distinction in the list as well.
